/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lesIHM;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author jean.aguirre2
 */
public class IHMajout extends javax.swing.JPanel {

    /**
     * Creates new form IHMajout
     */
    public IHMajout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListeAjoutType = new javax.swing.JComboBox<>();
        txtAjoutId = new javax.swing.JLabel();
        txtAjoutType = new javax.swing.JLabel();
        txtAjoutLogin = new javax.swing.JLabel();
        txtAjoutMDP = new javax.swing.JLabel();
        txtAjoutAdresse = new javax.swing.JLabel();
        txtAjoutCP = new javax.swing.JLabel();
        txtAjoutVille = new javax.swing.JLabel();
        txtAjoutDateEmbauche = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        ListeAjoutType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visiteur", "Comptable", "Admin" }));

        txtAjoutId.setText("ID de l'utilisateur :");

        txtAjoutType.setText("Je voudrais créer un :");

        txtAjoutLogin.setText("Login de l'utilisateur :");

        txtAjoutMDP.setText("Mot de passe de l'utilisateur :");

        txtAjoutAdresse.setText("Adresse de l'utilisateur :");

        txtAjoutCP.setText("Code postal de l'utilisateur :");

        txtAjoutVille.setText("Ville de l'utilisateur :");

        txtAjoutDateEmbauche.setText("Date d'embauche de l'utilisateur :");

        jLabel1.setText("Nom de l'utilisateur");

        jLabel3.setText("Prénom de l'utilisateur");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAjoutType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListeAjoutType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAjoutMDP)
                            .addComponent(txtAjoutVille)
                            .addComponent(txtAjoutDateEmbauche)
                            .addComponent(txtAjoutLogin)
                            .addComponent(txtAjoutAdresse)
                            .addComponent(txtAjoutCP))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(txtAjoutId))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListeAjoutType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAjoutType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAjoutId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAjoutLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAjoutMDP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAjoutAdresse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAjoutCP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAjoutVille)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAjoutDateEmbauche)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ListeAjoutType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txtAjoutAdresse;
    private javax.swing.JLabel txtAjoutCP;
    private javax.swing.JLabel txtAjoutDateEmbauche;
    private javax.swing.JLabel txtAjoutId;
    private javax.swing.JLabel txtAjoutLogin;
    private javax.swing.JLabel txtAjoutMDP;
    private javax.swing.JLabel txtAjoutType;
    private javax.swing.JLabel txtAjoutVille;
    // End of variables declaration//GEN-END:variables
}
